apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helixmind.fullname" . }}-secret
  labels:
    {{- include "helixmind.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.env.DATABASE_URL }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | b64enc | quote }}
  {{- else }}
  DATABASE_URL: {{ printf "postgresql://%s@%s-postgres:5432/%s?schema=public" .Values.postgresql.auth.username (include "helixmind.fullname" .) .Values.postgresql.auth.database | b64enc | quote }}
  {{- end }}
  NEXTAUTH_SECRET: {{ .Values.env.NEXTAUTH_SECRET | b64enc | quote }}
  AUTH_SECRET: {{ .Values.env.AUTH_SECRET | b64enc | quote }}
  STRIPE_SECRET_KEY: {{ .Values.env.STRIPE_SECRET_KEY | b64enc | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.env.STRIPE_WEBHOOK_SECRET | b64enc | quote }}
  GITHUB_CLIENT_ID: {{ .Values.env.GITHUB_CLIENT_ID | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.env.GITHUB_CLIENT_SECRET | b64enc | quote }}
  RESEND_API_KEY: {{ .Values.env.RESEND_API_KEY | b64enc | quote }}
