// Real brain data extracted from HelixMind demo project
// Contains 130 nodes and 122 edges from a live spiral memory

export interface DemoNode {
  id: string;
  label: string;
  type: string;
  level: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
  relevanceScore: number;
}

export interface DemoEdge {
  source: string;
  target: string;
  type: string;
  weight: number;
}

export const demoNodes: DemoNode[] = [
  { id: 'node-0', label: 'desktop_camera.py (123 lines)', type: 'code', level: 1, relevanceScore: 1 },
  { id: 'node-1', label: 'README.txt (41 lines)', type: 'code', level: 1, relevanceScore: 1 },
  { id: 'node-2', label: 'start_camera.bat (56 lines)', type: 'code', level: 1, relevanceScore: 1 },
  { id: 'node-3', label: 'Project Architecture', type: 'architecture', level: 1, relevanceScore: 1 },
  { id: 'node-4', label: 'Python Best Practices', type: 'pattern', level: 1, relevanceScore: 1 },
  { id: 'node-5', label: 'Tool Integration Tests', type: 'pattern', level: 1, relevanceScore: 1 },
  { id: 'node-6', label: 'Python virtual camera OBS', type: 'pattern', level: 1, relevanceScore: 1 },
  { id: 'node-7', label: 'Python virtual camera OBS', type: 'pattern', level: 1, relevanceScore: 1 },
  { id: 'node-8', label: 'Security Monitor Active', type: 'pattern', level: 1, relevanceScore: 1 },
  { id: 'node-9', label: 'Claim Check Pattern', type: 'decision', level: 1, relevanceScore: 0.999 },
  { id: 'node-10', label: 'Review Code Coverage (2)', type: 'code', level: 1, relevanceScore: 0.999 },
  { id: 'node-11', label: 'Fix Layout Shift (4)', type: 'code', level: 1, relevanceScore: 0.999 },
  { id: 'node-12', label: 'Review Error Logs (3)', type: 'code', level: 1, relevanceScore: 0.999 },
  { id: 'node-13', label: 'Fastify Hook System (2)', type: 'pattern', level: 1, relevanceScore: 0.999 },
  { id: 'node-14', label: 'GSAP ScrollTrigger (2)', type: 'pattern', level: 1, relevanceScore: 0.999 },
  { id: 'node-15', label: 'Fix Latency Spike (3)', type: 'code', level: 1, relevanceScore: 0.998 },
  { id: 'node-16', label: 'Add Context Menu (4)', type: 'code', level: 1, relevanceScore: 0.998 },
  { id: 'node-17', label: 'Update A/B Config (2)', type: 'code', level: 1, relevanceScore: 0.998 },
  { id: 'node-18', label: 'Kinde Organization Auth', type: 'pattern', level: 1, relevanceScore: 0.998 },
  { id: 'node-19', label: 'Audio Recorder Feature', type: 'code', level: 1, relevanceScore: 0.997 },
  { id: 'node-20', label: 'Fix URL Shortening (2)', type: 'code', level: 1, relevanceScore: 0.997 },
  { id: 'node-21', label: 'Deploy to Staging (4)', type: 'code', level: 1, relevanceScore: 0.997 },
  { id: 'node-22', label: 'Assignment Distribution (3)', type: 'code', level: 1, relevanceScore: 0.997 },
  { id: 'node-23', label: 'Fix Responsive Issue (3)', type: 'code', level: 2, relevanceScore: 0.699 },
  { id: 'node-24', label: 'Add Social Login', type: 'code', level: 2, relevanceScore: 0.699 },
  { id: 'node-25', label: 'Kustomize Overlays', type: 'pattern', level: 2, relevanceScore: 0.699 },
  { id: 'node-26', label: 'Dashboard Redesign (2)', type: 'code', level: 2, relevanceScore: 0.699 },
  { id: 'node-27', label: 'Fix Exit Animation (3)', type: 'code', level: 2, relevanceScore: 0.699 },
  { id: 'node-28', label: 'Dark Mode Toggle (4)', type: 'code', level: 2, relevanceScore: 0.698 },
  { id: 'node-29', label: 'PDF Generation Service (5)', type: 'code', level: 2, relevanceScore: 0.698 },
  { id: 'node-30', label: 'Post-Mortem Culture', type: 'decision', level: 2, relevanceScore: 0.698 },
  { id: 'node-31', label: 'Update Tests (5)', type: 'code', level: 2, relevanceScore: 0.698 },
  { id: 'node-32', label: 'Notification System (4)', type: 'code', level: 2, relevanceScore: 0.697 },
  { id: 'node-33', label: 'Fix Stack Trace (2)', type: 'code', level: 2, relevanceScore: 0.697 },
  { id: 'node-34', label: 'Scoring Algorithm (4)', type: 'code', level: 2, relevanceScore: 0.697 },
  { id: 'node-35', label: 'Date/Time Localization (2)', type: 'pattern', level: 2, relevanceScore: 0.697 },
  { id: 'node-36', label: 'WebTransport Protocol (2)', type: 'pattern', level: 2, relevanceScore: 0.696 },
  { id: 'node-37', label: 'Fix Resource Waste (4)', type: 'code', level: 2, relevanceScore: 0.696 },
  { id: 'node-38', label: 'Message Queue Design', type: 'decision', level: 2, relevanceScore: 0.696 },
  { id: 'node-39', label: 'SVG Animation Techniques', type: 'pattern', level: 2, relevanceScore: 0.696 },
  { id: 'node-40', label: 'Composite Pattern', type: 'decision', level: 2, relevanceScore: 0.695 },
  { id: 'node-41', label: 'Headless UI v2', type: 'pattern', level: 2, relevanceScore: 0.694 },
  { id: 'node-42', label: 'Implement Download Queue', type: 'code', level: 2, relevanceScore: 0.694 },
  { id: 'node-43', label: 'PBKDF2 Key Derivation', type: 'pattern', level: 2, relevanceScore: 0.693 },
  { id: 'node-44', label: 'Add Context Menu (2)', type: 'code', level: 2, relevanceScore: 0.693 },
  { id: 'node-45', label: 'Honeycomb BubbleUp (3)', type: 'pattern', level: 2, relevanceScore: 0.693 },
  { id: 'node-46', label: 'Review Feature Usage (2)', type: 'code', level: 2, relevanceScore: 0.692 },
  { id: 'node-47', label: 'Fix Animation Frame', type: 'code', level: 2, relevanceScore: 0.692 },
  { id: 'node-48', label: 'Workbox Runtime Caching', type: 'pattern', level: 2, relevanceScore: 0.692 },
  { id: 'node-49', label: 'PayPal Commerce Platform (2)', type: 'pattern', level: 2, relevanceScore: 0.691 },
  { id: 'node-50', label: 'Fix Header/Footer', type: 'code', level: 2, relevanceScore: 0.691 },
  { id: 'node-51', label: 'Fix Spam Score (3)', type: 'code', level: 2, relevanceScore: 0.69 },
  { id: 'node-52', label: 'Implement Retry Logic (4)', type: 'code', level: 2, relevanceScore: 0.69 },
  { id: 'node-53', label: 'Update Deployment (3)', type: 'code', level: 3, relevanceScore: 0.5 },
  { id: 'node-54', label: 'Hono RPC Patterns', type: 'pattern', level: 3, relevanceScore: 0.5 },
  { id: 'node-55', label: 'Bun Package Manager', type: 'pattern', level: 3, relevanceScore: 0.499 },
  { id: 'node-56', label: 'Update Field Config (2)', type: 'code', level: 3, relevanceScore: 0.498 },
  { id: 'node-57', label: 'Pulumi AI Features (2)', type: 'pattern', level: 3, relevanceScore: 0.498 },
  { id: 'node-58', label: 'Fumadocs Framework (2)', type: 'pattern', level: 3, relevanceScore: 0.497 },
  { id: 'node-59', label: 'Image Gallery Component', type: 'code', level: 3, relevanceScore: 0.496 },
  { id: 'node-60', label: 'Luxon Zone Management', type: 'pattern', level: 3, relevanceScore: 0.496 },
  { id: 'node-61', label: 'Check DKIM Setup (2)', type: 'code', level: 3, relevanceScore: 0.496 },
  { id: 'node-62', label: 'Audio Recorder Feature (3)', type: 'code', level: 3, relevanceScore: 0.496 },
  { id: 'node-63', label: 'Ambassador Pattern', type: 'decision', level: 3, relevanceScore: 0.496 },
  { id: 'node-64', label: 'Review CDN Performance', type: 'code', level: 3, relevanceScore: 0.495 },
  { id: 'node-65', label: 'Add Keyboard Navigation', type: 'code', level: 3, relevanceScore: 0.495 },
  { id: 'node-66', label: 'Cache API Strategies', type: 'pattern', level: 3, relevanceScore: 0.495 },
  { id: 'node-67', label: 'vLLM Deployment Guide (3)', type: 'pattern', level: 3, relevanceScore: 0.495 },
  { id: 'node-68', label: 'Date Picker Enhancement (5)', type: 'code', level: 3, relevanceScore: 0.494 },
  { id: 'node-69', label: 'Better Auth Rising', type: 'pattern', level: 3, relevanceScore: 0.494 },
  { id: 'node-70', label: 'Yarn Berry Plugins (2)', type: 'pattern', level: 3, relevanceScore: 0.494 },
  { id: 'node-71', label: 'Auth Middleware Refactor (4)', type: 'code', level: 3, relevanceScore: 0.494 },
  { id: 'node-72', label: 'Search Feature Enhancement', type: 'code', level: 3, relevanceScore: 0.493 },
  { id: 'node-73', label: 'Sharp Image Processing', type: 'pattern', level: 3, relevanceScore: 0.493 },
  { id: 'node-74', label: 'Auth.js v5 Migration (2)', type: 'pattern', level: 3, relevanceScore: 0.493 },
  { id: 'node-75', label: 'Breadcrumb Navigation (2)', type: 'code', level: 3, relevanceScore: 0.493 },
  { id: 'node-76', label: 'Hono Edge Handlers', type: 'pattern', level: 3, relevanceScore: 0.492 },
  { id: 'node-77', label: 'CSS Cascade Layers (2)', type: 'pattern', level: 3, relevanceScore: 0.492 },
  { id: 'node-78', label: 'EdgeStore Setup (2)', type: 'pattern', level: 3, relevanceScore: 0.492 },
  { id: 'node-79', label: 'Search Feature Enhancement (5)', type: 'code', level: 3, relevanceScore: 0.492 },
  { id: 'node-80', label: 'OpenTofu Progress (2)', type: 'pattern', level: 3, relevanceScore: 0.492 },
  { id: 'node-81', label: 'Fix Animation Frame (3)', type: 'code', level: 3, relevanceScore: 0.491 },
  { id: 'node-82', label: 'Update TTL Values (3)', type: 'code', level: 3, relevanceScore: 0.491 },
  { id: 'node-83', label: 'Puppeteer to @react-pdf PDF generation', type: 'code', level: 4, relevanceScore: 0.588 },
  { id: 'node-84', label: 'Offset to cursor-based pagination', type: 'pattern', level: 4, relevanceScore: 0.578 },
  { id: 'node-85', label: 'Outbox pattern for webhook delivery', type: 'pattern', level: 4, relevanceScore: 0.574 },
  { id: 'node-86', label: 'REST to GraphQL gateway migration', type: 'architecture', level: 4, relevanceScore: 0.562 },
  { id: 'node-87', label: 'Joi to Zod schema validation', type: 'code', level: 4, relevanceScore: 0.555 },
  { id: 'node-88', label: 'Shared to per-tenant schema isolation', type: 'architecture', level: 4, relevanceScore: 0.55 },
  { id: 'node-89', label: 'Redux to Zustand state management migr', type: 'pattern', level: 4, relevanceScore: 0.536 },
  { id: 'node-90', label: 'Docusaurus to Starlight docs migration', type: 'decision', level: 4, relevanceScore: 0.535 },
  { id: 'node-91', label: 'JWT refresh to sliding sessions', type: 'decision', level: 4, relevanceScore: 0.514 },
  { id: 'node-92', label: 'Dual build system Vite + esbuild', type: 'architecture', level: 4, relevanceScore: 0.508 },
  { id: 'node-93', label: 'ImageMagick to Sharp image processing', type: 'code', level: 4, relevanceScore: 0.499 },
  { id: 'node-94', label: 'moment.js to date-fns migration', type: 'code', level: 4, relevanceScore: 0.498 },
  { id: 'node-95', label: 'Legacy REST API v1 (Express to Koa mig', type: 'architecture', level: 4, relevanceScore: 0.497 },
  { id: 'node-96', label: 'Mocha/Chai to Vitest test framework mi', type: 'code', level: 4, relevanceScore: 0.491 },
  { id: 'node-97', label: 'Deprecated utility functions replaced', type: 'code', level: 4, relevanceScore: 0.487 },
  { id: 'node-98', label: 'Validation matrix: 60/30/10 catch rate', type: 'decision', level: 5, relevanceScore: 0.399 },
  { id: 'node-99', label: 'JSON WebSocket over protobuf for debug', type: 'pattern', level: 5, relevanceScore: 0.392 },
  { id: 'node-100', label: 'Three.js Points > InstancedMesh for 50', type: 'pattern', level: 5, relevanceScore: 0.371 },
  { id: 'node-101', label: 'Background sessions for context switch', type: 'decision', level: 5, relevanceScore: 0.366 },
  { id: 'node-102', label: 'Checkpoint system from git stash study', type: 'decision', level: 5, relevanceScore: 0.363 },
  { id: 'node-103', label: 'YOLO mode for experienced developers', type: 'decision', level: 5, relevanceScore: 0.362 },
  { id: 'node-104', label: 'Chrome-finder cross-platform detection', type: 'pattern', level: 5, relevanceScore: 0.359 },
  { id: 'node-105', label: 'MiniLM-L6-v2 matches ada-002 at 95%', type: 'pattern', level: 5, relevanceScore: 0.356 },
  { id: 'node-106', label: 'Permission model inspired by VS Code/D', type: 'decision', level: 5, relevanceScore: 0.344 },
  { id: 'node-107', label: 'GPT-3.5 to Claude migration for tool-u', type: 'pattern', level: 5, relevanceScore: 0.33 },
  { id: 'node-108', label: 'Spiral memory from hippocampal researc', type: 'decision', level: 5, relevanceScore: 0.325 },
  { id: 'node-109', label: 'DuckDuckGo: keyless search for enrichm', type: 'pattern', level: 5, relevanceScore: 0.321 },
  { id: 'node-110', label: 'MiniLM embeddings for semantic search', type: 'pattern', level: 6, relevanceScore: 0.249 },
  { id: 'node-111', label: 'adm-zip ZIP archive library', type: 'pattern', level: 6, relevanceScore: 0.249 },
  { id: 'node-112', label: 'fast-glob file discovery library', type: 'pattern', level: 6, relevanceScore: 0.247 },
  { id: 'node-113', label: 'CLI permission model best practices', type: 'pattern', level: 6, relevanceScore: 0.246 },
  { id: 'node-114', label: 'Path traversal prevention techniques', type: 'pattern', level: 6, relevanceScore: 0.244 },
  { id: 'node-115', label: 'DuckDuckGo API for web research', type: 'pattern', level: 6, relevanceScore: 0.24 },
  { id: 'node-116', label: 'Git checkpoint system design', type: 'pattern', level: 6, relevanceScore: 0.235 },
  { id: 'node-117', label: 'GPU particle system techniques', type: 'pattern', level: 6, relevanceScore: 0.234 },
  { id: 'node-118', label: 'sqlite-vec KNN search benchmarks', type: 'pattern', level: 6, relevanceScore: 0.234 },
  { id: 'node-119', label: 'Three.js custom ShaderMaterial tutoria', type: 'pattern', level: 6, relevanceScore: 0.233 },
  { id: 'node-120', label: 'WebSocket protocol deep dive', type: 'pattern', level: 6, relevanceScore: 0.226 },
  { id: 'node-121', label: 'Commander.js v13 CLI framework docs', type: 'pattern', level: 6, relevanceScore: 0.211 },
  { id: 'node-122', label: 'chalk v5 ESM migration guide', type: 'pattern', level: 6, relevanceScore: 0.21 },
  { id: 'node-123', label: 'AGPL-3.0 license analysis', type: 'pattern', level: 6, relevanceScore: 0.207 },
  { id: 'node-124', label: 'nanospinner CLI spinner library', type: 'pattern', level: 6, relevanceScore: 0.205 },
  { id: 'node-125', label: 'Fix: EBUSY on Windows SQLite WAL clean', type: 'pattern', level: 6, relevanceScore: 0.197 },
  { id: 'node-126', label: 'TypeScript 5.5 decorator metadata', type: 'pattern', level: 6, relevanceScore: 0.195 },
  { id: 'node-127', label: 'CSP header configuration guide', type: 'pattern', level: 6, relevanceScore: 0.194 },
  { id: 'node-128', label: 'WebSocket reconnection strategy', type: 'pattern', level: 6, relevanceScore: 0.188 },
  { id: 'node-129', label: 'MDN Web Workers API documentation', type: 'pattern', level: 6, relevanceScore: 0.184 },
];

export const demoEdges: DemoEdge[] = [
  { source: 'node-12', target: 'node-53', type: 'supports', weight: 0.3 },
  { source: 'node-28', target: 'node-16', type: 'supports', weight: 0.93 },
  { source: 'node-11', target: 'node-27', type: 'inspired_by', weight: 0.25 },
  { source: 'node-26', target: 'node-71', type: 'references', weight: 0.38 },
  { source: 'node-18', target: 'node-76', type: 'evolved_from', weight: 0.23 },
  { source: 'node-54', target: 'node-39', type: 'extends', weight: 0.15 },
  { source: 'node-63', target: 'node-38', type: 'extends', weight: 0.76 },
  { source: 'node-40', target: 'node-38', type: 'depends_on', weight: 0.15 },
  { source: 'node-40', target: 'node-9', type: 'depends_on', weight: 0.73 },
  { source: 'node-9', target: 'node-40', type: 'inspired_by', weight: 0.33 },
  { source: 'node-9', target: 'node-30', type: 'implements', weight: 0.48 },
  { source: 'node-49', target: 'node-55', type: 'implements', weight: 0.93 },
  { source: 'node-47', target: 'node-68', type: 'uses', weight: 0.58 },
  { source: 'node-75', target: 'node-77', type: 'extends', weight: 0.41 },
  { source: 'node-48', target: 'node-63', type: 'inspired_by', weight: 0.27 },
  { source: 'node-18', target: 'node-30', type: 'contradicts', weight: 0.84 },
  { source: 'node-39', target: 'node-9', type: 'uses', weight: 0.94 },
  { source: 'node-82', target: 'node-26', type: 'uses', weight: 0.15 },
  { source: 'node-64', target: 'node-30', type: 'implements', weight: 0.84 },
  { source: 'node-64', target: 'node-30', type: 'references', weight: 0.31 },
  { source: 'node-20', target: 'node-45', type: 'contradicts', weight: 0.82 },
  { source: 'node-26', target: 'node-78', type: 'implements', weight: 0.49 },
  { source: 'node-43', target: 'node-74', type: 'evolved_from', weight: 0.1 },
  { source: 'node-77', target: 'node-67', type: 'extends', weight: 0.69 },
  { source: 'node-95', target: 'node-97', type: 'extends', weight: 0.23 },
  { source: 'node-95', target: 'node-89', type: 'related_to', weight: 0.39 },
  { source: 'node-97', target: 'node-89', type: 'depends_on', weight: 0.31 },
  { source: 'node-97', target: 'node-106', type: 'related_to', weight: 0.58 },
  { source: 'node-89', target: 'node-96', type: 'depends_on', weight: 0.61 },
  { source: 'node-96', target: 'node-106', type: 'evolved_from', weight: 0.22 },
  { source: 'node-106', target: 'node-107', type: 'uses', weight: 0.51 },
  { source: 'node-106', target: 'node-89', type: 'inspired_by', weight: 0.72 },
  { source: 'node-86', target: 'node-88', type: 'contradicts', weight: 0.22 },
  { source: 'node-86', target: 'node-105', type: 'supports', weight: 0.33 },
  { source: 'node-86', target: 'node-102', type: 'inspired_by', weight: 0.26 },
  { source: 'node-86', target: 'node-99', type: 'references', weight: 0.4 },
  { source: 'node-86', target: 'node-101', type: 'inspired_by', weight: 0.28 },
  { source: 'node-86', target: 'node-104', type: 'extends', weight: 0.43 },
  { source: 'node-93', target: 'node-88', type: 'supports', weight: 0.38 },
  { source: 'node-93', target: 'node-98', type: 'related_to', weight: 0.32 },
  { source: 'node-93', target: 'node-102', type: 'contradicts', weight: 0.37 },
  { source: 'node-93', target: 'node-109', type: 'extends', weight: 0.63 },
  { source: 'node-94', target: 'node-84', type: 'inspired_by', weight: 0.55 },
  { source: 'node-94', target: 'node-108', type: 'extends', weight: 0.5 },
  { source: 'node-94', target: 'node-102', type: 'implements', weight: 0.49 },
  { source: 'node-94', target: 'node-99', type: 'references', weight: 0.34 },
  { source: 'node-94', target: 'node-104', type: 'inspired_by', weight: 0.33 },
  { source: 'node-92', target: 'node-101', type: 'extends', weight: 0.64 },
  { source: 'node-92', target: 'node-109', type: 'uses', weight: 0.24 },
  { source: 'node-91', target: 'node-87', type: 'implements', weight: 0.61 },
  { source: 'node-91', target: 'node-88', type: 'supports', weight: 0.15 },
  { source: 'node-87', target: 'node-84', type: 'related_to', weight: 0.41 },
  { source: 'node-87', target: 'node-105', type: 'supports', weight: 0.5 },
  { source: 'node-87', target: 'node-102', type: 'depends_on', weight: 0.58 },
  { source: 'node-87', target: 'node-101', type: 'supports', weight: 0.28 },
  { source: 'node-84', target: 'node-83', type: 'supports', weight: 0.49 },
  { source: 'node-84', target: 'node-85', type: 'inspired_by', weight: 0.41 },
  { source: 'node-84', target: 'node-102', type: 'related_to', weight: 0.62 },
  { source: 'node-84', target: 'node-103', type: 'related_to', weight: 0.38 },
  { source: 'node-84', target: 'node-104', type: 'related_to', weight: 0.35 },
  { source: 'node-90', target: 'node-85', type: 'references', weight: 0.37 },
  { source: 'node-90', target: 'node-99', type: 'related_to', weight: 0.55 },
  { source: 'node-90', target: 'node-101', type: 'evolved_from', weight: 0.19 },
  { source: 'node-90', target: 'node-109', type: 'uses', weight: 0.32 },
  { source: 'node-90', target: 'node-104', type: 'references', weight: 0.55 },
  { source: 'node-83', target: 'node-108', type: 'extends', weight: 0.29 },
  { source: 'node-83', target: 'node-105', type: 'references', weight: 0.25 },
  { source: 'node-83', target: 'node-101', type: 'inspired_by', weight: 0.6 },
  { source: 'node-83', target: 'node-109', type: 'uses', weight: 0.55 },
  { source: 'node-85', target: 'node-108', type: 'supports', weight: 0.46 },
  { source: 'node-85', target: 'node-102', type: 'references', weight: 0.56 },
  { source: 'node-85', target: 'node-101', type: 'references', weight: 0.58 },
  { source: 'node-85', target: 'node-109', type: 'references', weight: 0.5 },
  { source: 'node-85', target: 'node-103', type: 'depends_on', weight: 0.17 },
  { source: 'node-108', target: 'node-98', type: 'evolved_from', weight: 0.49 },
  { source: 'node-108', target: 'node-109', type: 'references', weight: 0.25 },
  { source: 'node-108', target: 'node-103', type: 'uses', weight: 0.65 },
  { source: 'node-108', target: 'node-104', type: 'contradicts', weight: 0.55 },
  { source: 'node-105', target: 'node-99', type: 'contradicts', weight: 0.27 },
  { source: 'node-105', target: 'node-100', type: 'related_to', weight: 0.17 },
  { source: 'node-98', target: 'node-102', type: 'evolved_from', weight: 0.54 },
  { source: 'node-98', target: 'node-101', type: 'depends_on', weight: 0.2 },
  { source: 'node-102', target: 'node-99', type: 'inspired_by', weight: 0.17 },
  { source: 'node-102', target: 'node-100', type: 'evolved_from', weight: 0.48 },
  { source: 'node-102', target: 'node-104', type: 'extends', weight: 0.28 },
  { source: 'node-99', target: 'node-101', type: 'inspired_by', weight: 0.36 },
  { source: 'node-99', target: 'node-100', type: 'implements', weight: 0.53 },
  { source: 'node-99', target: 'node-103', type: 'uses', weight: 0.27 },
  { source: 'node-109', target: 'node-104', type: 'related_to', weight: 0.16 },
  { source: 'node-86', target: 'node-38', type: 'references', weight: 0.37 },
  { source: 'node-86', target: 'node-63', type: 'supports', weight: 0.45 },
  { source: 'node-84', target: 'node-38', type: 'references', weight: 0.36 },
  { source: 'node-88', target: 'node-38', type: 'references', weight: 0.47 },
  { source: 'node-85', target: 'node-40', type: 'references', weight: 0.23 },
  { source: 'node-108', target: 'node-92', type: 'inspired_by', weight: 0.66 },
  { source: 'node-108', target: 'node-84', type: 'inspired_by', weight: 0.78 },
  { source: 'node-108', target: 'node-93', type: 'inspired_by', weight: 0.61 },
  { source: 'node-105', target: 'node-96', type: 'inspired_by', weight: 0.77 },
  { source: 'node-105', target: 'node-87', type: 'inspired_by', weight: 0.7 },
  { source: 'node-105', target: 'node-40', type: 'supports', weight: 0.32 },
  { source: 'node-98', target: 'node-96', type: 'inspired_by', weight: 0.55 },
  { source: 'node-98', target: 'node-95', type: 'inspired_by', weight: 0.71 },
  { source: 'node-99', target: 'node-91', type: 'inspired_by', weight: 0.58 },
  { source: 'node-99', target: 'node-93', type: 'inspired_by', weight: 0.73 },
  { source: 'node-99', target: 'node-63', type: 'references', weight: 0.33 },
  { source: 'node-101', target: 'node-88', type: 'inspired_by', weight: 0.69 },
  { source: 'node-100', target: 'node-96', type: 'inspired_by', weight: 0.48 },
  { source: 'node-104', target: 'node-85', type: 'inspired_by', weight: 0.44 },
  { source: 'node-104', target: 'node-63', type: 'references', weight: 0.35 },
  { source: 'node-125', target: 'node-122', type: 'related_to', weight: 0.66 },
  { source: 'node-128', target: 'node-119', type: 'related_to', weight: 0.7 },
  { source: 'node-119', target: 'node-110', type: 'related_to', weight: 0.54 },
  { source: 'node-118', target: 'node-113', type: 'related_to', weight: 0.51 },
  { source: 'node-118', target: 'node-115', type: 'related_to', weight: 0.33 },
  { source: 'node-113', target: 'node-116', type: 'related_to', weight: 0.36 },
  { source: 'node-120', target: 'node-114', type: 'related_to', weight: 0.4 },
  { source: 'node-117', target: 'node-111', type: 'related_to', weight: 0.64 },
  { source: 'node-117', target: 'node-124', type: 'related_to', weight: 0.43 },
  { source: 'node-111', target: 'node-112', type: 'related_to', weight: 0.47 },
  { source: 'node-111', target: 'node-124', type: 'related_to', weight: 0.34 },
  { source: 'node-123', target: 'node-92', type: 'inspired_by', weight: 0.12 },
  { source: 'node-7', target: 'node-6', type: 'related_to', weight: 0.79 },
];
